# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-15 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20190921_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultrecord',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Customer', verbose_name='所跟进客户'),
        ),
    ]
