# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-10-15 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20191015_0918'),
        ('crm', '0003_auto_20191015_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.User'),
        ),
    ]
